name: Container Security Scan
on:
  workflow_run:
    workflows: ["Deploy to Registry"]
    types: [completed]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: "ghcr.io/${{ github.repository }}/backend:latest"
          format: "table"
          exit-code: "1"
          severity: "CRITICAL,HIGH"

      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: "ghcr.io/${{ github.repository }}/frontend:latest"
          format: "table"
          exit-code: "1"
          severity: "CRITICAL,HIGH"
